### PR TITLE
Add ftdomdelegate resolution

### PR DESCRIPTION
**Pull request by remybach**
🐿 v2.12.3

### CODE REVIEW

**Comment by umbobabo** [comment]
@remybach I didn't follow all the discussion around ftdomdelegate, would you mind helping me to understand why this is necessary? I think it would be beneficial maybe to others.

**Comment by remybach** [comment]
Basically, there are many sub-dependencies within our projects... some of which specify different versions of `ftdomdelegate`. It normally pauses in the CLI and asks you to choose which version you want to install but since we can't do that in CI, we need to add this resolution to the config manually.

**Comment by liamkeaton** [comment]
Origami are working through them but there seems to be quite a few https://github.com/Financial-Times/o-overlay/pull/186

**Comment by umbobabo** [comment]
Thank you for the explanation @remybach  @liamkeaton . FYI @CourtneyLO @richardLuko @jkerr321

**Pull request merged**
